name: Build and Deploy to Production

on:
  push:
    branches:
      - main
env:
  AWS_S3_BUCKET: web.direct
jobs:
  deploy:
    name: Deploy assets to Amazon S3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: set-env
        uses: allenevans/set-env@v2.0.0
        with:
          NUXT_POLLEN_PASS_URL: ${{ secrets.POLLEN_PASS_URL }}
          NUXT_POLLEN_PASS_URL_PROD: ${{ secrets.POLLEN_PASS_URL_PROD }}
          NUXT_POLLEN_LMS_URL: ${{ secrets.POLLEN_LMS_URL }}
          NUXT_POLLEN_LMS_URL_PROD: ${{ secrets.POLLEN_LMS_URL_PROD }}
          NUXT_DIRECT_API: ${{ secrets.DIRECT_API }}
      - name: Clean up
        run: yarn clean:nuxt

      - name: Build SPA
        run: yarn generate

      - name: Sync assets to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: "ASIAZKDIC63XCQKQ4NMT"
          AWS_SECRET_ACCESS_KEY: "TqAEfMh2lu8JZL2HcwCanHT9KYTYA3WPBYm"
          AWS_REGION: "ap-southeast-1" # optional: defaults to us-east-1
          SOURCE_DIR: ".output/public"

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          PATHS: "/*"
          AWS_REGION: "ap-southeast-1"
          DISTRIBUTION: "E2BX391S9D7VRQ"
          AWS_ACCESS_KEY_ID: "AKIAZKDIC63XOQPCN6OG"
          AWS_SECRET_ACCESS_KEY: "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"
